
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,
	
	//////////// BUTTON //////////
	input [2:0] BTN,
	
	//////////// RS232 ///////////
	input RX,
	output TX
	
);
//*******************************//

rs232 f_rs232(.TX(TX), .RX(RX), .clk(CLK), .rst(!BTN[0]));

//*******************************//

endmodule
